name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
env: 
  APP_KEYS: mBUu5KYMQqrl8GAT/D4VYg==,O+OFu9V21gziY9DLw6h1VA==,RIB1x09quecLID8HBnpxMw==,eyTM/IO/oigZCN3F2ICYdg==
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with: 
          node-version: 16
      - run: yarn install
      - run: yarn build
      - run: yarn start
